[package]
name = "gitlab"
version = "0.1208.1"
authors = ["Ben Boeckel <ben.boeckel@kitware.com>"]
license = "MIT/Apache-2.0"
description = """
Gitlab API client.
"""
repository = "https://gitlab.kitware.com/utils/rust-gitlab"
documentation = "https://docs.rs/gitlab/0.1208.1"
readme = "README.md"
keywords = ["gitlab", "api"]
categories = ["web-programming", "api-bindings"]
edition = "2018"

[dependencies]
derive_builder = "~0.9"
itertools = "~0.8"
log = "~0.4"
percent-encoding = "^2.0"
reqwest = { version = "~0.10", features = ["blocking", "json"] }
rustversion = "^1.0"
thiserror = "^1.0.2"
url = "2.1"

chrono = { version = "~0.4", features = ["serde"] }
graphql_client = "~0.8"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "^1.0"
