[package]
name = "gitlab"
version = "0.1.0"
authors = ["Ben Boeckel <ben.boeckel@kitware.com>"]
license = "MIT/Apache-2.0"
description = """
Gitlab API client.
"""
repository = "https://gitlab.kitware.com/utils/rust-gitlab.git"
homepage = "https://gitlab.kitware.com/utils/rust-gitlab"
readme = "README.md"
build = "build.rs"

[build-dependencies]
serde_codegen = "~0.7"

[dependencies]
chrono = { version = "~0.2, <=0.2.23", features = ["serde"] }
ease = "~0.5"
hyper = "~0.9"
log = "*"
serde = "~0.7"
serde_json = "~0.7"
url = "~1.1"
