[package]
name = "gitlab"
version = "0.1.0"
authors = ["Ben Boeckel <ben.boeckel@kitware.com>"]
license = "MIT/Apache-2.0"
description = """
Gitlab API client.
"""
repository = "https://gitlab.kitware.com/utils/rust-gitlab"
documentation = "https://docs.rs/gitlab/~0.1"
readme = "README.md"

[dependencies]
chrono = { version = "~0.3", features = ["serde"] }
error-chain = "~0.9"
hyper = { version = "~0.10", default-features = false }
log = "~0.3"
reqwest = "~0.4"
serde = "~0.9"
serde_derive = "~0.9"
serde_json = "~0.9"
url = "~1.4"
