[package]
name = "gitlab"
version = "0.1206.0"
authors = ["Ben Boeckel <ben.boeckel@kitware.com>"]
license = "MIT/Apache-2.0"
description = """
Gitlab API client.
"""
repository = "https://gitlab.kitware.com/utils/rust-gitlab"
documentation = "https://docs.rs/gitlab/0.1206.0"
readme = "README.md"
keywords = ["gitlab", "api"]
categories = ["web-programming", "api-bindings"]

[dependencies]
itertools = "~0.8"
log = "~0.4"
percent-encoding = "^2.0"
reqwest = "~0.9"
rustversion = "^1.0"
thiserror = "^1.0.2"
derive_builder = "~0.9"
chrono = { version = "~0.4", features = ["serde"] }
serde = { version = "~1.0", features = ["derive"] }
serde_json = "^1.0"
